spring:
    profiles:
        activate:
            on-profile: cloud
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        properties:
            hibernate:
                format_sql: true
    jackson:
        time-zone: America/Sao_Paulo
      
---

spring:
    profiles:
        activate:
            on-profile: default
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: user
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        properties:
            hibernate:
                format_sql: true
    jackson:
        time-zone: America/Sao_Paulo
server:
    port: 8181